#!/usr/bin/env node
// Copyright (c) 2026 Alex Baretta. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root.
// Traceability: verifies REQ-PONYTAIL-PROJECT-ISOLATION

const assert = require('node:assert/strict');
const fs = require('node:fs');
const crypto = require('node:crypto');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');

const root = path.join(__dirname, '..');
const tool = path.join(root, 'cli', 'condense_codex_rules.sh');
const installer = path.join(root, 'scripts', 'install-cli.sh');

function temporaryRoot(name) {
  return fs.mkdtempSync(path.join(os.tmpdir(), `${name}-`));
}

function writeProject(project, policy) {
  fs.mkdirSync(path.join(project, '.agents/config'), { recursive: true });
  fs.writeFileSync(path.join(project, '.agents/config', 'codex-execpolicy.json'), `${JSON.stringify({
    schemaVersion: 1,
    safe: [],
    unsafe: [],
    ...policy,
  }, null, 2)}\n`);
}

function run(home, args = [], input = '') {
  return spawnSync(tool, ['--home', home, ...args], {
    encoding: 'utf8',
    env: { ...process.env, HOME: home },
    input,
  });
}

function statePath(home) {
  return path.join(home, '.ponytail', 'codex-execpolicy', 'state.json');
}

function rulesPath(home) {
  return path.join(home, '.codex', 'rules', 'ponytail.rules');
}

function projectStatePath(home, project) {
  const canonical = fs.realpathSync(project);
  const key = crypto.createHash('sha256').update(canonical).digest('hex');
  return path.join(home, '.ponytail', 'codex-execpolicy', 'projects', `${key}.json`);
}

function projectRulesPath(project) {
  return path.join(project, '.codex', 'rules', 'ponytail.rules');
}

test('declined and noninteractive proposals leave user state unchanged', () => {
  const home = temporaryRoot('ponytail-policy-home');
  const project = temporaryRoot('ponytail-policy-project');
  writeProject(project, {
    safe: [{ pattern: ['./scripts/test.sh'], justification: 'Run the project test entrypoint' }],
  });

  let result = run(home, ['--project', project]);
  assert.equal(result.status, 2, result.stderr);
  assert.match(result.stderr, /Codex execpolicy proposal:/);
  assert.match(result.stderr, /proposal digest: [a-f0-9]{64}/);
  assert.match(result.stderr, /policy unchanged/);
  assert.equal(fs.existsSync(statePath(home)), false);
  assert.equal(fs.existsSync(rulesPath(home)), false);
  assert.equal(fs.existsSync(projectStatePath(home, project)), false);
  assert.equal(fs.existsSync(projectRulesPath(project)), false);

  result = run(home, ['--project', project], 'n\n');
  assert.equal(result.status, 2, result.stderr);
  assert.equal(fs.existsSync(statePath(home)), false);
});

test('accepts imported, baseline, and project rules into reconstructible state', () => {
  const home = temporaryRoot('ponytail-policy-home');
  const project = temporaryRoot('ponytail-policy-project');
  const codexRules = path.join(home, '.codex', 'rules');
  fs.mkdirSync(codexRules, { recursive: true });
  fs.writeFileSync(path.join(codexRules, 'default.rules'), [
    'prefix_rule(pattern=["curl", "-fsSL", "https://example.test"], decision="allow")',
    'prefix_rule(pattern=["git", "add", "one"], decision="allow")',
    '',
  ].join('\n'));
  writeProject(project, {
    safe: [{ pattern: ['./scripts/test.sh'], justification: 'Run the project test entrypoint' }],
    unsafe: [{ pattern: ['./scripts/install.sh'], decision: 'prompt', justification: 'Changes shared user state' }],
  });

  const result = run(home, ['--project', project], 'yes\n');
  assert.equal(result.status, 0, result.stderr);
  const state = JSON.parse(fs.readFileSync(statePath(home), 'utf8'));
  assert.equal(state.schemaVersion, 3);
  assert.match(state.proposalDigest, /^[a-f0-9]{64}$/);
  assert.ok(state.importedRules.some(({ pattern }) => pattern.includes('curl')));
  assert.equal(new Set(state.acceptedRules.map((rule) => JSON.stringify(rule))).size, state.acceptedRules.length);
  assert.ok(state.acceptedRules.every(({ pattern }) => pattern.join(' ') !== 'git add one'));
  assert.ok(state.acceptedRules.some(({ pattern, sources }) => pattern.join(' ') === 'git add' && sources.some((source) => source.startsWith('codex-import:'))));
  assert.ok(state.acceptedRules.some(({ decision, pattern }) => decision === 'forbidden' && pattern.join(' ') === `rm -rf ${fs.realpathSync(home)}`));
  assert.ok(state.acceptedRules.every(({ pattern }) => pattern.join(' ') !== 'rm -rf'));
  assert.ok(state.acceptedRules.every(({ sources }) => sources.every((source) => !source.startsWith('project:'))));
  const generated = fs.readFileSync(rulesPath(home), 'utf8');
  assert.match(generated, /Generated by Ponytail/);
  assert.match(generated, /https:\/\/example\.test/);
  assert.match(generated, /decision="forbidden"/);
  assert.doesNotMatch(generated, /\.\/scripts\/(test|install)\.sh/);
  const projectState = JSON.parse(fs.readFileSync(projectStatePath(home, project), 'utf8'));
  assert.equal(projectState.schemaVersion, 1);
  assert.equal(projectState.projectRoot, fs.realpathSync(project));
  assert.ok(projectState.acceptedRules.some(({ decision, pattern }) => decision === 'prompt' && pattern[0] === './scripts/install.sh'));
  const projectGenerated = fs.readFileSync(projectRulesPath(project), 'utf8');
  assert.match(projectGenerated, /\.\/scripts\/test\.sh/);
  assert.match(projectGenerated, /\.\/scripts\/install\.sh/);
  assert.doesNotMatch(projectGenerated, /example\.test/);
  assert.equal(run(home, ['--project', project, '--check']).status, 0);
});

test('changed project policy requires its exact new proposal digest', () => {
  const home = temporaryRoot('ponytail-policy-home');
  const project = temporaryRoot('ponytail-policy-project');
  writeProject(project, {});
  assert.equal(run(home, ['--project', project], 'y\n').status, 0);

  writeProject(project, {
    safe: [{ pattern: ['./scripts/lint.sh'], justification: 'Run the project lint entrypoint' }],
  });
  let result = run(home, ['--project', project, '--check']);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /current proposals do not match accepted state/);

  result = run(home, ['--project', project, '--dry-run']);
  assert.equal(result.status, 0, result.stderr);
  const digest = result.stderr.match(/proposal digest: ([a-f0-9]{64})/)[1];
  assert.notEqual(run(home, ['--project', project, '--accept', '0'.repeat(64)]).status, 0);
  assert.equal(run(home, ['--project', project, '--accept', digest]).status, 0);
  assert.equal(run(home, ['--project', project, '--check']).status, 0);
});

test('restores Codex rules from accepted Ponytail state', () => {
  const home = temporaryRoot('ponytail-policy-home');
  const project = temporaryRoot('ponytail-policy-project');
  writeProject(project, { safe: [{ pattern: ['./scripts/local.sh'], justification: 'Run locally' }] });
  assert.equal(run(home, ['--project', project], 'y\n').status, 0);
  const accepted = fs.readFileSync(rulesPath(home), 'utf8');
  const projectAccepted = fs.readFileSync(projectRulesPath(project), 'utf8');
  fs.rmSync(path.join(home, '.codex'), { recursive: true });
  fs.rmSync(path.join(project, '.codex'), { recursive: true });

  const result = run(home, ['--project', project, '--restore']);
  assert.equal(result.status, 0, result.stderr);
  assert.equal(fs.readFileSync(rulesPath(home), 'utf8'), accepted);
  assert.equal(fs.readFileSync(projectRulesPath(project), 'utf8'), projectAccepted);
});

test('upgrades V1 accepted state without reading foreign project worktrees', () => {
  const home = temporaryRoot('ponytail-policy-home');
  const project = temporaryRoot('ponytail-policy-project');
  const foreign = '/missing/foreign-project';
  writeProject(project, {
    safe: [{ pattern: ['./scripts/local.sh'], justification: 'Run the local project command' }],
  });
  fs.mkdirSync(path.dirname(statePath(home)), { recursive: true });
  fs.writeFileSync(statePath(home), `${JSON.stringify({
    schemaVersion: 1,
    projects: [foreign],
    projectDigests: { [foreign]: '1'.repeat(64) },
    importedRules: [],
    acceptedRules: [{
      pattern: ['./scripts/foreign.sh'],
      decision: 'allow',
      justification: 'Previously accepted foreign command',
      sources: [`project:${foreign}`],
    }],
    proposalDigest: '2'.repeat(64),
  }, null, 2)}\n`);

  const result = run(home, ['--project', project], 'yes\n');
  assert.equal(result.status, 0, result.stderr);
  const state = JSON.parse(fs.readFileSync(statePath(home), 'utf8'));
  assert.equal(state.schemaVersion, 3);
  assert.ok(state.acceptedRules.every(({ sources }) => sources.every((source) => !source.startsWith('project:'))));
  assert.ok(state.acceptedRules.every(({ pattern }) => pattern[0] !== './scripts/foreign.sh'));
  const localState = JSON.parse(fs.readFileSync(projectStatePath(home, project), 'utf8'));
  assert.ok(localState.acceptedRules.some(({ pattern }) => pattern[0] === './scripts/local.sh'));
  assert.ok(localState.acceptedRules.every(({ pattern }) => pattern[0] !== './scripts/foreign.sh'));
});

test('V2 migration ignores malformed foreign accepted project data', () => {
  const home = temporaryRoot('ponytail-policy-home');
  const project = temporaryRoot('ponytail-policy-project');
  const canonical = fs.realpathSync(project);
  writeProject(project, { safe: [{ pattern: ['./scripts/local.sh'], justification: 'Run local' }] });
  fs.mkdirSync(path.dirname(statePath(home)), { recursive: true });
  fs.writeFileSync(statePath(home), `${JSON.stringify({
    schemaVersion: 2,
    projectPolicies: {
      '/missing/foreign-project': { malformed: true },
      [canonical]: { digest: '1'.repeat(64), rules: [{ pattern: ['./scripts/old-local.sh'], decision: 'allow', justification: 'Old local', sources: [`project:${canonical}`] }] },
    },
    legacyProjectDigests: { '/another/foreign-project': 'not-a-digest' },
    legacyRules: [{ malformed: true }],
    importedRules: [],
    acceptedRules: [{ malformed: true }],
    proposalDigest: 'not-a-digest',
  }, null, 2)}\n`);

  const result = run(home, ['--project', project], 'yes\n');
  assert.equal(result.status, 0, result.stderr);
  assert.equal(JSON.parse(fs.readFileSync(statePath(home))).schemaVersion, 3);
  assert.match(fs.readFileSync(projectRulesPath(project), 'utf8'), /local\.sh/);
  assert.doesNotMatch(fs.readFileSync(rulesPath(home), 'utf8'), /old-local|foreign/);
});

test('keeps project policies in separate project-local projections', () => {
  const home = temporaryRoot('ponytail-policy-home');
  const first = temporaryRoot('ponytail-policy-first');
  const second = temporaryRoot('ponytail-policy-second');
  writeProject(first, { safe: [{ pattern: ['./scripts/first.sh'], justification: 'Run first' }] });
  writeProject(second, { safe: [{ pattern: ['./scripts/second.sh'], justification: 'Run second' }] });
  assert.equal(run(home, ['--project', first], 'y\n').status, 0);
  const globalState = fs.readFileSync(statePath(home), 'utf8');
  const globalRules = fs.readFileSync(rulesPath(home), 'utf8');
  assert.equal(run(home, ['--project', second], 'y\n').status, 0);
  const firstRules = fs.readFileSync(projectRulesPath(first), 'utf8');
  const secondRules = fs.readFileSync(projectRulesPath(second), 'utf8');
  assert.match(firstRules, /first\.sh/);
  assert.doesNotMatch(firstRules, /second\.sh/);
  assert.match(secondRules, /second\.sh/);
  assert.doesNotMatch(secondRules, /first\.sh/);
  assert.doesNotMatch(fs.readFileSync(rulesPath(home), 'utf8'), /first\.sh|second\.sh/);
  assert.equal(fs.readFileSync(statePath(home), 'utf8'), globalState);
  assert.equal(fs.readFileSync(rulesPath(home), 'utf8'), globalRules);

  writeProject(first, { safe: [{ pattern: ['./scripts/first-new.sh'], justification: 'Run changed first' }] });
  assert.equal(run(home, ['--project', first], 'y\n').status, 0);
  assert.equal(fs.readFileSync(projectRulesPath(second), 'utf8'), secondRules);
});

test('rejects symlinked policy outputs and malformed project directives', () => {
  const home = temporaryRoot('ponytail-policy-home');
  const project = temporaryRoot('ponytail-policy-project');
  writeProject(project, {
    unsafe: [{ pattern: ['rm'], decision: 'allow', justification: 'Invalid unsafe decision' }],
  });
  let result = run(home, ['--project', project], 'y\n');
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /unsafe\[0\]\.decision is invalid/);

  writeProject(project, {});
  assert.equal(run(home, ['--project', project], 'y\n').status, 0);
  fs.rmSync(rulesPath(home));
  fs.symlinkSync(path.join(home, 'outside.rules'), rulesPath(home));
  result = run(home, ['--project', project, '--restore']);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /refusing to replace non-regular or symlink path/);
});

test('is installable as a selected Ponytail CLI tool', () => {
  const home = temporaryRoot('ponytail-policy-install-home');
  const result = spawnSync(installer, ['condense_codex_rules.sh'], {
    encoding: 'utf8',
    env: { ...process.env, HOME: home, PATH: '/usr/bin:/bin' },
    input: 'n\n',
  });

  assert.equal(result.status, 0, result.stderr);
  const installed = path.join(home, '.local', 'bin', 'condense_codex_rules.sh');
  assert.ok(fs.statSync(installed).mode & 0o100);
  assert.equal(spawnSync(installed, ['--help'], { encoding: 'utf8' }).status, 0);
});
